// Auto-generated by VIP Connect Bot — do not edit manually
// To update, post changes in the event's Slack channel

export const eventConfig = {
  "city": "Ha Long Bay",
  "venue": "Ha Long Bay, Vietnam",
  "capacity": 30,
  "eventTitle": "VIP Connect — Ha Long Bay Leadership Dinner",
  "heroImageUrl": "/venue/long-table.png",
  "heroHeadline": "VIP Connect",
  "heroSubheadline": "Ha Long Bay Leadership Dinner",
  "heroDescription": "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",
  "experienceHeadline": "Thirty leaders.\\nA UNESCO World Heritage bay.\\nNo slides.",
  "experienceParagraphs": [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other’s assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What’s working, what’s not, and what the next twelve months look like.",
    "We gather at Ha Long Bay, where Vietnam's gaming leaders connect against one of nature's most spectacular backdrops."
  ],
  "agendaItems": [
    {
      "time": "12:00 PM",
      "title": "Arrival & Welcome Drinks",
      "description": "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small."
    },
    {
      "time": "12:30 PM",
      "title": "Executive Session",
      "description": "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like."
    },
    {
      "time": "12:45 PM",
      "title": "Dinner",
      "description": "A curated Vietnamese feast featuring the finest coastal cuisine while surrounded by the bay's legendary limestone formations."
    },
    {
      "time": "3:00 PM",
      "title": "Event Close",
      "description": "An informal close as the evening winds down."
    }
  ],
  "agendaShort": [
    {
      "time": "12:00 PM",
      "label": "Arrival & welcome drinks"
    },
    {
      "time": "12:30 PM",
      "label": "Executive session"
    },
    {
      "time": "12:45 PM",
      "label": "Dinner"
    },
    {
      "time": "3:00 PM",
      "label": "Event close"
    }
  ],
  "faqItems": [
    {
      "q": "What is Moloco VIP Connect?",
      "a": "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion."
    },
    {
      "q": "Who is this event for?",
      "a": "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 30 people. Small enough that everyone speaks, diverse enough that you’ll hear something that changes how you think about a problem."
    },
    {
      "q": "Is this a public event / can I bring a +1?",
      "a": "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link."
    },
    {
      "q": "What should I wear?",
      "a": "Smart casual. Polished but comfortable. Think what you’d wear to dinner with people you want to impress without looking like you tried."
    },
    {
      "q": "Is there a cost to attend?",
      "a": "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco."
    },
    {
      "q": "What about dietary requirements?",
      "a": "Ha Long Bay, Vietnam accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they’ll take care of it."
    }
  ],
  "calendarTitle": "Moloco VIP Connect — Ha Long Bay Leadership Dinner",
  "calendarUidPrefix": "moloco-vip-connect-2026",
  "siteUrl": "https://moloco-event-ha-long-bay.vercel.app",
  "slug": "moloco-event-ha-long-bay",
  "eventSubtitle": "An exclusive retreat for Vietnam's gaming executives",
  "venueAddress": "Ha Long Bay, Quang Ninh Province",
  "venueAddressFull": "Ha Long Bay, Quang Ninh Province, Vietnam",
  "date": "May 21, 2024",
  "dateFull": "Tuesday, May 21",
  "dateISO": "2024-05-21",
  "calendarDateStart": "20240521T120000",
  "calendarDateEnd": "20240521T150000",
  "time": "12:00 PM",
  "timezone": "Asia/Ho_Chi_Minh",
  "timezoneAbbr": "ICT",
  "venueDescription": "Ha Long Bay's emerald waters and towering limestone karsts create one of the world's natural wonders. This UNESCO World Heritage site offers a breathtaking backdrop where ancient geological formations meet modern luxury. The bay's mystical atmosphere provides an unparalleled setting for meaningful connections away from the everyday.",
  "venueCapacityNote": "An intimate gathering space aboard a luxury vessel with panoramic bay views.",
  "venueDiningNote": "Vietnamese coastal cuisine featuring fresh seafood and regional specialties.",
  "venueDirections": "Located approximately 165km from Hanoi's city center, accessible via private helicopter transfer or luxury coach service to Ha Long Bay harbor. boarding details will be provided with confirmation.",
  "venueExperienceLine": "We gather at Ha Long Bay, where Vietnam's gaming leaders connect against one of nature's most spectacular backdrops.",
  "dinnerDescription": "A curated Vietnamese feast featuring the finest coastal cuisine while surrounded by the bay's legendary limestone formations.",
  "mapsUrl": "https://maps.google.com/search/Ha+Long+Bay,+Quang+Ninh+Province,+Vietnam"
};
